import { createFileRoute, notFound } from '@tanstack/react-router'
import { isLocale, type Locale } from '#/lib/i18n'
import { HomePage } from '#/components/HomePage'
import {
  alternateLinks,
  localeUrl,
  localizedSeo,
  OG_LOCALE,
  SITE_URL,
} from '#/lib/seo'

// Localized share cards (generated by scripts/make-share-card.mjs). Each is a
// 1200x630 PNG whose copy matches the locale's hero, so a link shared from a
// /<locale> page previews in that language on Slack / X / WhatsApp / Telegram /
// LinkedIn. Overriding og:image + twitter:image here wins over the root's
// default English card because TanStack keeps the last entry for a duplicated
// meta `property`/`name`.
const SHARE_CARD_ALT: Record<Locale, string> = {
  en: 'Battery Sensei: quiet battery care for your MacBook',
  de: 'Battery Sensei: ruhige Akkupflege für dein MacBook',
  es: 'Battery Sensei: cuidado silencioso para la batería de tu Mac',
  fr: 'Battery Sensei : soin discret pour la batterie de votre Mac',
  ja: 'Battery Sensei：静かなバッテリーケア',
}

/**
 * Localized home pages: /de, /es, /fr, /ja. English lives at "/" (not "/en").
 * The root beforeLoad has already loaded the matching locale bundle and set the
 * active language from the path, so the body and <html lang> render localized;
 * here we only validate the segment and emit localized meta + hreflang.
 */
export const Route = createFileRoute('/$lang')({
  beforeLoad: ({ params }) => {
    if (!isLocale(params.lang) || params.lang === 'en') throw notFound()
  },
  head: ({ params }) => {
    const locale = params.lang as Locale
    const { title, description } = localizedSeo(locale)
    const url = localeUrl(locale)
    const card = `${SITE_URL}/share-card-${locale}.png`
    const cardAlt = SHARE_CARD_ALT[locale]
    return {
      meta: [
        { title },
        { name: 'description', content: description },
        { property: 'og:title', content: title },
        { property: 'og:description', content: description },
        { property: 'og:url', content: url },
        { property: 'og:locale', content: OG_LOCALE[locale] },
        { property: 'og:image', content: card },
        { property: 'og:image:alt', content: cardAlt },
        { name: 'twitter:title', content: title },
        { name: 'twitter:description', content: description },
        { name: 'twitter:image', content: card },
        { name: 'twitter:image:alt', content: cardAlt },
      ],
      links: [{ rel: 'canonical', href: url }, ...alternateLinks()],
    }
  },
  component: HomePage,
})
