/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalkthroughRouteImport } from './routes/walkthrough'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlossaryIndexRouteImport } from './routes/glossary/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ThanksSupportRouteImport } from './routes/thanks.support'
import { Route as ThanksLifetimeRouteImport } from './routes/thanks.lifetime'
import { Route as GlossarySlugRouteImport } from './routes/glossary/$slug'
import { Route as FeaturesTravelModeRouteImport } from './routes/features.travel-mode'
import { Route as FeaturesMeetingBatteryGuardRouteImport } from './routes/features.meeting-battery-guard'
import { Route as FeaturesEnergyUsageRouteImport } from './routes/features.energy-usage'
import { Route as FeaturesCustomThresholdsRouteImport } from './routes/features.custom-thresholds'
import { Route as FeaturesBatteryJournalRouteImport } from './routes/features.battery-journal'
import { Route as FeaturesAlertPresetsRouteImport } from './routes/features.alert-presets'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiCheckoutIdRouteImport } from './routes/api/checkout.$id'

const WalkthroughRoute = WalkthroughRouteImport.update({
  id: '/walkthrough',
  path: '/walkthrough',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksSupportRoute = ThanksSupportRouteImport.update({
  id: '/thanks/support',
  path: '/thanks/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksLifetimeRoute = ThanksLifetimeRouteImport.update({
  id: '/thanks/lifetime',
  path: '/thanks/lifetime',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarySlugRoute = GlossarySlugRouteImport.update({
  id: '/glossary/$slug',
  path: '/glossary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesTravelModeRoute = FeaturesTravelModeRouteImport.update({
  id: '/features/travel-mode',
  path: '/features/travel-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesMeetingBatteryGuardRoute =
  FeaturesMeetingBatteryGuardRouteImport.update({
    id: '/features/meeting-battery-guard',
    path: '/features/meeting-battery-guard',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesEnergyUsageRoute = FeaturesEnergyUsageRouteImport.update({
  id: '/features/energy-usage',
  path: '/features/energy-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesCustomThresholdsRoute =
  FeaturesCustomThresholdsRouteImport.update({
    id: '/features/custom-thresholds',
    path: '/features/custom-thresholds',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesBatteryJournalRoute = FeaturesBatteryJournalRouteImport.update({
  id: '/features/battery-journal',
  path: '/features/battery-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesAlertPresetsRoute = FeaturesAlertPresetsRouteImport.update({
  id: '/features/alert-presets',
  path: '/features/alert-presets',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutIdRoute = ApiCheckoutIdRouteImport.update({
  id: '/api/checkout/$id',
  path: '/api/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/walkthrough': typeof WalkthroughRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/alert-presets': typeof FeaturesAlertPresetsRoute
  '/features/battery-journal': typeof FeaturesBatteryJournalRoute
  '/features/custom-thresholds': typeof FeaturesCustomThresholdsRoute
  '/features/energy-usage': typeof FeaturesEnergyUsageRoute
  '/features/meeting-battery-guard': typeof FeaturesMeetingBatteryGuardRoute
  '/features/travel-mode': typeof FeaturesTravelModeRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/thanks/lifetime': typeof ThanksLifetimeRoute
  '/thanks/support': typeof ThanksSupportRoute
  '/blog/': typeof BlogIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/api/checkout/$id': typeof ApiCheckoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/walkthrough': typeof WalkthroughRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/alert-presets': typeof FeaturesAlertPresetsRoute
  '/features/battery-journal': typeof FeaturesBatteryJournalRoute
  '/features/custom-thresholds': typeof FeaturesCustomThresholdsRoute
  '/features/energy-usage': typeof FeaturesEnergyUsageRoute
  '/features/meeting-battery-guard': typeof FeaturesMeetingBatteryGuardRoute
  '/features/travel-mode': typeof FeaturesTravelModeRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/thanks/lifetime': typeof ThanksLifetimeRoute
  '/thanks/support': typeof ThanksSupportRoute
  '/blog': typeof BlogIndexRoute
  '/glossary': typeof GlossaryIndexRoute
  '/api/checkout/$id': typeof ApiCheckoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/walkthrough': typeof WalkthroughRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/features/alert-presets': typeof FeaturesAlertPresetsRoute
  '/features/battery-journal': typeof FeaturesBatteryJournalRoute
  '/features/custom-thresholds': typeof FeaturesCustomThresholdsRoute
  '/features/energy-usage': typeof FeaturesEnergyUsageRoute
  '/features/meeting-battery-guard': typeof FeaturesMeetingBatteryGuardRoute
  '/features/travel-mode': typeof FeaturesTravelModeRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/thanks/lifetime': typeof ThanksLifetimeRoute
  '/thanks/support': typeof ThanksSupportRoute
  '/blog/': typeof BlogIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/api/checkout/$id': typeof ApiCheckoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/legal'
    | '/privacy'
    | '/walkthrough'
    | '/blog/$slug'
    | '/features/alert-presets'
    | '/features/battery-journal'
    | '/features/custom-thresholds'
    | '/features/energy-usage'
    | '/features/meeting-battery-guard'
    | '/features/travel-mode'
    | '/glossary/$slug'
    | '/thanks/lifetime'
    | '/thanks/support'
    | '/blog/'
    | '/glossary/'
    | '/api/checkout/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/legal'
    | '/privacy'
    | '/walkthrough'
    | '/blog/$slug'
    | '/features/alert-presets'
    | '/features/battery-journal'
    | '/features/custom-thresholds'
    | '/features/energy-usage'
    | '/features/meeting-battery-guard'
    | '/features/travel-mode'
    | '/glossary/$slug'
    | '/thanks/lifetime'
    | '/thanks/support'
    | '/blog'
    | '/glossary'
    | '/api/checkout/$id'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/legal'
    | '/privacy'
    | '/walkthrough'
    | '/blog/$slug'
    | '/features/alert-presets'
    | '/features/battery-journal'
    | '/features/custom-thresholds'
    | '/features/energy-usage'
    | '/features/meeting-battery-guard'
    | '/features/travel-mode'
    | '/glossary/$slug'
    | '/thanks/lifetime'
    | '/thanks/support'
    | '/blog/'
    | '/glossary/'
    | '/api/checkout/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  WalkthroughRoute: typeof WalkthroughRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FeaturesAlertPresetsRoute: typeof FeaturesAlertPresetsRoute
  FeaturesBatteryJournalRoute: typeof FeaturesBatteryJournalRoute
  FeaturesCustomThresholdsRoute: typeof FeaturesCustomThresholdsRoute
  FeaturesEnergyUsageRoute: typeof FeaturesEnergyUsageRoute
  FeaturesMeetingBatteryGuardRoute: typeof FeaturesMeetingBatteryGuardRoute
  FeaturesTravelModeRoute: typeof FeaturesTravelModeRoute
  GlossarySlugRoute: typeof GlossarySlugRoute
  ThanksLifetimeRoute: typeof ThanksLifetimeRoute
  ThanksSupportRoute: typeof ThanksSupportRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GlossaryIndexRoute: typeof GlossaryIndexRoute
  ApiCheckoutIdRoute: typeof ApiCheckoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/walkthrough': {
      id: '/walkthrough'
      path: '/walkthrough'
      fullPath: '/walkthrough'
      preLoaderRoute: typeof WalkthroughRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks/support': {
      id: '/thanks/support'
      path: '/thanks/support'
      fullPath: '/thanks/support'
      preLoaderRoute: typeof ThanksSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks/lifetime': {
      id: '/thanks/lifetime'
      path: '/thanks/lifetime'
      fullPath: '/thanks/lifetime'
      preLoaderRoute: typeof ThanksLifetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/$slug': {
      id: '/glossary/$slug'
      path: '/glossary/$slug'
      fullPath: '/glossary/$slug'
      preLoaderRoute: typeof GlossarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/travel-mode': {
      id: '/features/travel-mode'
      path: '/features/travel-mode'
      fullPath: '/features/travel-mode'
      preLoaderRoute: typeof FeaturesTravelModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/meeting-battery-guard': {
      id: '/features/meeting-battery-guard'
      path: '/features/meeting-battery-guard'
      fullPath: '/features/meeting-battery-guard'
      preLoaderRoute: typeof FeaturesMeetingBatteryGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/energy-usage': {
      id: '/features/energy-usage'
      path: '/features/energy-usage'
      fullPath: '/features/energy-usage'
      preLoaderRoute: typeof FeaturesEnergyUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/custom-thresholds': {
      id: '/features/custom-thresholds'
      path: '/features/custom-thresholds'
      fullPath: '/features/custom-thresholds'
      preLoaderRoute: typeof FeaturesCustomThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/battery-journal': {
      id: '/features/battery-journal'
      path: '/features/battery-journal'
      fullPath: '/features/battery-journal'
      preLoaderRoute: typeof FeaturesBatteryJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/alert-presets': {
      id: '/features/alert-presets'
      path: '/features/alert-presets'
      fullPath: '/features/alert-presets'
      preLoaderRoute: typeof FeaturesAlertPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/$id': {
      id: '/api/checkout/$id'
      path: '/api/checkout/$id'
      fullPath: '/api/checkout/$id'
      preLoaderRoute: typeof ApiCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  WalkthroughRoute: WalkthroughRoute,
  BlogSlugRoute: BlogSlugRoute,
  FeaturesAlertPresetsRoute: FeaturesAlertPresetsRoute,
  FeaturesBatteryJournalRoute: FeaturesBatteryJournalRoute,
  FeaturesCustomThresholdsRoute: FeaturesCustomThresholdsRoute,
  FeaturesEnergyUsageRoute: FeaturesEnergyUsageRoute,
  FeaturesMeetingBatteryGuardRoute: FeaturesMeetingBatteryGuardRoute,
  FeaturesTravelModeRoute: FeaturesTravelModeRoute,
  GlossarySlugRoute: GlossarySlugRoute,
  ThanksLifetimeRoute: ThanksLifetimeRoute,
  ThanksSupportRoute: ThanksSupportRoute,
  BlogIndexRoute: BlogIndexRoute,
  GlossaryIndexRoute: GlossaryIndexRoute,
  ApiCheckoutIdRoute: ApiCheckoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
